version: '3'
services:
  sw1:
    container_name: arista-sw1
    image: keppel.eu-de-1.cloud.sap/ccloud/arista-ceos:4.26.4M
    command: /sbin/init systemd.setenv=INTFTYPE=eth systemd.setenv=ETBA=4
      systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 systemd.setenv=CEOS=1
      systemd.setenv=EOS_PLATFORM=ceoslab systemd.setenv=container=docker
      systemd.setenv=MAPETH0=1
    networks:
      - net1
      - net2
    privileged: true
    volumes:
      - ${PWD}/testlab/arista/config-arista-sw1:/mnt/flash/startup-config
    environment:
      - container=docker
      - INTFTYPE=eth
      - ETBA=1
      - SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
      - CEOS=1
      - EOS_PLATFORM=ceoslab
      - MAPETH0=1

  sw2:
    container_name: arista-sw2
    image: keppel.eu-de-1.cloud.sap/ccloud/arista-ceos:4.26.4M
    command: /sbin/init systemd.setenv=INTFTYPE=eth systemd.setenv=ETBA=4
      systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1 systemd.setenv=CEOS=1
      systemd.setenv=EOS_PLATFORM=ceoslab systemd.setenv=container=docker
      systemd.setenv=MAPETH0=1
    networks:
      - net1
      - net2
    privileged: true
    volumes:
      - ${PWD}/testlab/arista/config-arista-sw2:/mnt/flash/startup-config
    environment:
      - container=docker
      - INTFTYPE=eth
      - ETBA=1
      - SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
      - CEOS=1
      - EOS_PLATFORM=ceoslab
      - MAPETH0=1

  k3s:
    container_name: k3s
    hostname: k3s
    image: rancher/k3s:v1.31.1-rc2-k3s1
    command: server --node-ip 10.0.0.10 --flannel-iface eth1
    networks:
      net1: null
      net2:
        ipv4_address: 10.0.0.10
    privileged: true
    environment:
      - K3S_TOKEN=foo
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ${PWD}/testlab/parrot/config:/etc/kubernetes/kube-parrot/config
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443

networks:
  net1: null
  net2:
    ipam:
      config:
        - subnet: 10.0.0.0/24
